package com.example.mushaf.constant

import com.example.mushaf.data.Surahs

object Constant {

    const val BASE_URI = "https://api.alquran.cloud/v1/surah/"


    val listOfSurahs = listOf(
        Surahs(id = 1 , surah = "الفاتحة"),
        Surahs(id = 2 , surah = "البقرة"),
        Surahs(id = 3 , surah = "آل عمران"),
        Surahs(id = 4 , surah = "النساء"),
        Surahs(id = 5 , surah = "المائدة"),
        Surahs(id = 6 , surah = "الأنعام"),
        Surahs(id = 7 , surah = "الأعراف"),
        Surahs(id = 8 , surah = "الأنفال"),
        Surahs(id = 9 , surah = "التوبة"),
        Surahs(id = 10 , surah = "يونس"),
        Surahs(id = 11 , surah = "هود"),
        Surahs(id = 12 , surah = "يوسف"),
        Surahs(id = 13 , surah = "الرعد"),
        Surahs(id = 14 , surah = "إبراهيم"),
        Surahs(id = 15 , surah = "الحجر"),
        Surahs(id = 16 , surah = "النحل"),
        Surahs(id = 17, surah = "الإسراء"),
        Surahs(id = 18 , surah = "الكهف"),
        Surahs(id = 19 , surah = "مريم"),
        Surahs(id = 20 , surah = "طه"),
        Surahs(id = 21 , surah = "الأنبياء"),
        Surahs(id = 22 , surah = "الحج"),
        Surahs(id = 23 , surah = "المؤمنون"),
        Surahs(id = 24 , surah = "النور"),
        Surahs(id = 25 , surah = "الفرقان"),
        Surahs(id = 26 , surah = "الشعراء"),
        Surahs(id = 27 , surah = "النمل"),
        Surahs(id = 28 , surah = "القصص"),
        Surahs(id = 29 , surah = "العنكبوت"),
        Surahs(id = 30 , surah = "الروم"),
        Surahs(id = 31 , surah = "لقمان"),
        Surahs(id = 32 , surah = "السجدة"),
        Surahs(id = 33 , surah = "الأحزاب"),
        Surahs(id = 34 , surah = "سبأ"),
        Surahs(id = 35 , surah = "فاطر"),
        Surahs(id = 36 , surah = "يس"),
        Surahs(id = 37 , surah = "الصافات"),
        Surahs(id = 38 , surah = "ص"),
        Surahs(id = 39, surah = "الزمر"),
        Surahs(id = 40 , surah = "غافر"),
        Surahs(id = 41 , surah = "فصلت"),
        Surahs(id = 42 , surah = "الشورى"),
        Surahs(id = 43 , surah = "الزخرف"),
        Surahs(id = 44 , surah = "الدخان"),
        Surahs(id = 45 , surah = "الجاثية"),
        Surahs(id = 46 , surah = "الأحقاف"),
        Surahs(id = 47 , surah = "محمد"),
        Surahs(id = 48 , surah = "الفتح"),
        Surahs(id = 49, surah = "الحجرات"),
        Surahs(id = 50 , surah = "ق"),
        Surahs(id = 51 , surah = "الذاريات"),
        Surahs(id = 52 , surah = "الطور"),
        Surahs(id = 53 , surah = "النجم"),
        Surahs(id = 54 , surah = "القمر"),
        Surahs(id = 55 , surah = "الرحمن"),
        Surahs(id = 56 , surah = "الواقعة"),
        Surahs(id = 57 , surah = "الحديد"),
        Surahs(id = 58 , surah = "المجادلة"),
        Surahs(id = 59, surah = "الحشر"),
        Surahs(id = 60 , surah = "الممتحنة"),
        Surahs(id = 61 , surah = "الصف"),
        Surahs(id = 62 , surah = "الجمعة"),
        Surahs(id = 63 , surah = "المنافقون"),
        Surahs(id = 64 , surah = "التغابن"),
        Surahs(id = 65 , surah = "الطلاق"),
        Surahs(id = 66 , surah = "التحريم"),
        Surahs(id = 67 , surah = "الملك"),
        Surahs(id = 68 , surah = "القلم"),
        Surahs(id = 69, surah = "الحاقة"),
        Surahs(id = 70 , surah = "المعارج"),
        Surahs(id = 71 , surah = "نوح"),
        Surahs(id = 72 , surah = "الجن"),
        Surahs(id = 73 , surah = "المزمل"),
        Surahs(id = 74 , surah = "المدثر"),
        Surahs(id = 75 , surah = "القيامة"),
        Surahs(id = 76 , surah = "الإنسان"),
        Surahs(id = 77 , surah = "المرسلات"),
        Surahs(id = 78 , surah = "النبأ"),
        Surahs(id = 79, surah = "النازعات"),
        Surahs(id = 80 , surah = "عبس"),
        Surahs(id = 81 , surah = "التكوير"),
        Surahs(id = 82 , surah = "الانفطار"),
        Surahs(id = 83 , surah = "المطففين"),
        Surahs(id = 84 , surah = "الانشقاق"),
        Surahs(id = 85 , surah = "البروج"),
        Surahs(id = 86 , surah = "الطارق"),
        Surahs(id = 87 , surah = "الأعلى"),
        Surahs(id = 88 , surah = "الغاشية"),
        Surahs(id = 89, surah = "الفجر"),
        Surahs(id = 90 , surah = "البلد"),
        Surahs(id = 91 , surah = "الشمس"),
        Surahs(id = 92 , surah = "الليل"),
        Surahs(id = 93 , surah = "الضحى"),
        Surahs(id = 94 , surah = "الشرح"),
        Surahs(id = 95 , surah = "التين"),
        Surahs(id = 96 , surah = "العلق"),
        Surahs(id = 97 , surah = "القدر"),
        Surahs(id = 98 , surah = "البينة"),
        Surahs(id = 99, surah = "الزلزلة"),
        Surahs(id = 100 , surah = "العاديات"),
        Surahs(id = 101 , surah = "القارعة"),
        Surahs(id = 102, surah = "التكاثر"),
        Surahs(id = 103 , surah = "العصر"),
        Surahs(id = 104 , surah = "الهُمزة"),
        Surahs(id = 105 , surah = "الفيل"),
        Surahs(id = 106 , surah = "قريش"),
        Surahs(id = 107 , surah = "الماعون"),
        Surahs(id = 108 , surah = "الكوثر"),
        Surahs(id = 109, surah = "الكافرون"),
        Surahs(id = 110 , surah = "النصر"),
        Surahs(id = 111 , surah = "المسد"),
        Surahs(id = 112 , surah = "الإخلاص"),
        Surahs(id = 113 , surah = "الفلق"),
        Surahs(id = 114 , surah = "الناس"),
        )
}